services:
  - type: web
    name: djibril-tracking
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8765
      - key: TOKEN_SECRET
        value: djibril-tracking-secret-2026
